version : '3'
 
services:
    webserver:
        build: ./docker/php
        container_name: "web_zfuno"
        ports:
            - "8282:80"
            - "447:443"
        networks:
          zfuno-static-network:
                ipv4_address: 184.28.128.10
        volumes:
            - .:/var/www/html
            - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
        links:
            - mongodb
            - memcached
        depends_on:
            - mongodb
        command: sh /var/www/html/docker/php/init.sh
        
     
    mongodb:
        container_name: "mongodb_zfuno"
        image: bitnami/mongodb:latest
        ports:
            - "27022:27017"
        networks:
          zfuno-static-network:
                ipv4_address: 184.28.128.11
        environment:
            - MONGODB_ROOT_PASSWORD=toor
            - MONGODB_USERNAME=root
            - MONGODB_PASSWORD=root
            - MONGODB_DATABASE=mbd_zfuno
            
    memcached:
        container_name: "memcached_zfuno"
        image: memcached:alpine
        ports:
            - "11204:11211"
        networks:
          zfuno-static-network:
                ipv4_address: 184.28.128.12

networks:
  zfuno-static-network:
        ipam:
            config:
                - subnet: 184.28.0.0/16